version: 2
updates:
  # Github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"
    groups:
      # init/autobuild/analyze must stay on the same version or CodeQL errors out
      codeql-action:
        patterns:
          - "github/codeql-action*"

  # Root Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"

  # Root Go module
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "pandatix"
