before:
  hooks:
    - go mod tidy

gomod:
  proxy: true

builds:
  - main: ./cmd/victor
    binary: victor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - "ctfer-io/{{ .ProjectName }}:latest"
      - "ctfer-io/{{ .ProjectName }}:{{ .Tag }}"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

source:
  enabled: true

checksum: {}

sboms:
  - artifacts: source
